### ISSUE TITLE
正则表达式

### ISSUE THREAD

**Issue by 921** [evensandbox/blog#126]
### String
- string.search( regexp )
- string.replace( regexp, _replace ) || string.replace( regexp, function() {})
- string.match( regexp )
- string.split( regexp )
#### string.search

`string.search( regexp )` 当 regexp 参数不是正则表达式时, 进行转换为正则. 匹配到时, 返回匹配位置; 匹配不到, 返回 -1;

``` js
'abcabc'.search( /a/ ); // 0
'abcabcd'.search( /c(?=d)/ ); // 5
'abcabc'.search( /d/ ); // -1
```
#### string.replace

`string.replace( regexp, string )` 或者 `string.replace( regexp, function( match, $n, ..., index, string ) {});`

``` js
'abcabc'.replace( /a/, 'A' ); // 'Abcabc'
'abcabc'.replace( /a/g, 'A' ); // 'AbcAbc'
'abcabc'.replace( /(a)/g, '($1)' ); // '(a)bc(a)bc'
'abcabc'.replace( /(a)/g, '($&)' ); // '(a)bc(a)bc'
'abcabc'.replace( /(a)/g, '($\')' ); // '(bcabc)bc(bc)bc'
'abcabc'.replace( /(a)/g, '($`)' ); // '()bc(abc)bc'
'abcabc'.replace( /(a)/g, function( match, $1, index, string ) {
  console.log( match, $1, index, string ); 
  // 'a', 'a', 0, 'abcabc'
  // 'a', 'a', 3, 'abcabc'
});
```
#### string.match

`string.match( regexp )` 根据 regexp 的匹配模式, 存在两种情况.
1. 当 regexp 匹配模式为 `g`, 返回所有匹配结果.
2. 不为 `g` 时, 返回匹配结果和捕获结果.

``` js
'abcabcabc'.match( /a/g ); // [ 'a', 'a', 'a' ]
'abcabcabc'.match( /a/ ); // [ 'a' ]
'abcabcabc'.match( /(a)/ ); // [ 'a', 'a' ]
```
#### string.split

`string.split( regexp )` 函数作用是分隔字符. 所以它不匹配最开始或结束位置.
详解见 https://github.com/zhanhongtao/blog/issues/123
#### 构造函数

`new RegExp( string, pattern )` 中的 string 如果包含 `\` 字符, 需求使用 `\\` 转义. ex:

```
var reg = new RegExp( '\\d' );
reg.test( 'a2b' );
```

属性:
1. .global 是否为 `g` 模式.
2. .ignoreCase 是否为 `i` 模式.
3. .multiline 是否为 `m` 模式.
4. .lastIndex 当前开始匹配位置
5. .source 正则表达式字符串
- regexp.exec( string )
- regexp.test( string )

方法：
1. .exec( string )
2. .test( string )
#### regexp.exec

`regexp.exec( string )` 和 `string.match( regexp )` 不带 `g` 模式对应(只是对象和参数对调)
即 `regexp.exec` 会返回匹配值和捕获的值组成的数组. 同时 lastIndex 会更新.
`regexp.exec( string )` 使用时, regexp 是否加 `g` 与结果无关. 

``` js
var reg = /a/g;
reg.exec( 'abcabc' ); // [ 'a' ]
reg.lastIndex; // 1
reg.exec( 'abcabc' ); // [ 'a' ]
reg.lastIndex; // 4
/a/.exec( 'abcabc' ); // [ 'a' ]
```
#### regexp.test

`regexp.test( string )` 和 `regexp.exec( string )` 类似. 但它结果返回 Boolean 值.
lastIndex 索引值也会更新.

**Comment by evensandbox** [comment]
在读 mustach.js 源码时, 看到下面代码.

``` js
  function escapeRegExp(string) {
    return string.replace(/[\-\[\]{}()*+?.,\\\^$|#\s]/g, "\\$&");
  }
```

其中有 `$&` 表示匹配当前项. 出于好奇 Google 下还有没有其它类似指令.
搜索结果, 还有其它值可使用.
1. $` 匹配到的字符之前的全部字符.
2. $' 匹配到的字符之后的全部字符.

看下面例子:

``` js
'--1++'.replace( /1/, '$`' ); // ----++
'--1++'.replace( /1/, '$\''); // --++++
'-1+'.replace( /1/, '$&'); // -1+
```

还看到 RegExp 对象本身还存在一些(自己)不常用的属性.

### `RegExp.$1, RegExp.$2, ...., RegExp.$9`

``` js
/(.)(.)d/.test( 'abcabd' ); // true
RegExp.$1; // 'a'
RegExp.$2; // 'b'
```

### `RegExp.$_` 和 `RegExp.$input` 指向最后一次匹配的输入字符串.

``` js
// 还是上面的例子.
RegExp.$_; // 'abcabd'
RegExp.$input; // 'abcabd'
```

### 其它
- `RegExp.lastMatch` :  最后匹配字符.
- `RegExp.lastParen` : 最后捕获字符.
-  `RegExp.leftContext` : 匹配字符之前的全部字符 -> $`
- `RegExp.rightContext` : 匹配字符之后的全部字符 -> $'
- `RegExp.multiline` : 返回boolean, 表示是否为多行匹配

End!

**Comment by 921** [comment]
正则表达式中 \b 匹配一个位置: 它的前一个和后一个字符不全是 \w。
注意: 这里 \w 表示 [a-zA-Z_]

看下面例子

``` js
 var reg = /\bhi\b/;
'hi'.match( reg ); // [ 'hi' ]
'@hi'.match( reg ) // [ 'hi' ]
'_hi'.match( reg ) // null
```
