### ISSUE TITLE
Try markdown

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#185]
# Tasklist
- [x]  尝试使用 React/Vue
- [x] 学习并分享 ECMAScript 6
- [x] 学习使用 GitHub 网站中的功能
- [ ] 学习语法分析器
- [ ] UserScript 
- [x] Others

**Comment by zhanhongtao** [comment]
fixed #185

**Comment by evensandbox** [comment]
> 学习并分享 ECMAScript 6

呵呵
