### ISSUE TITLE
程序设计~

### ISSUE THREAD

**Issue by evensandbox** [evensandbox/blog#61]
下面语句是在知乎上看到的与如果学习/要不要学习数据结构和算法相关问题的评论.
- 比我差的人还没放弃，比我好的人仍在努力，我就更没资格说，我无能为力!
- 前端工程师也是程序员
- 提高编程能力 + 启发思维.
- 天赋决定上限,努力决定下限
- 好像也没什么工作是非要天赋才能做的
- 从大部分人的努力程度来看，还没有达到拼天赋的地步
- 以咱们大多数人的努力程度来看，根本没轮到拼天赋的时候。
- 优秀的程序员，都是通过展示自己的代码牛逼来展示自己的牛逼的。二逼的程序员，通过展示自己的工具

**Comment by ghost** [comment]
嗯，只是有的时候会无所适从，所以想找个自己的项目做做

**Comment by chilebaby** [comment]
思维很重要

**Comment by evensandbox** [comment]
@chilebaby 恩啊. :8ball:
